# Generated by Django 6.0.6 on 2026-07-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gesym', '0007_bodega_movimiento_bodega_producto_bodega'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('bodega', 'codigo')},
        ),
    ]
