# Generated by Django 6.0.6 on 2026-08-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesym', '0011_alter_empleadobodega_options_cliente_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_ingreso',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('bandeja', 'Bandeja')], default='unidad', max_length=10),
        ),
    ]
