# Generated by Django 6.0.6 on 2026-08-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesym', '0013_producto_numero_bandejas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_caja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_caja',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
