# Generated by Django 6.0.6 on 2026-07-09 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BodegaLamerica',
            fields=[
                ('id_bodega', models.IntegerField(db_column='Id_bodega', primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(db_column='Ubicacion', max_length=100)),
                ('capacidad_de_productos', models.IntegerField(db_column='Capacidad_de_productos')),
                ('productos', models.IntegerField(db_column='Productos')),
                ('nombre_de_encargado', models.CharField(db_column='Nombre_de_encargado', max_length=100)),
                ('id_empleado', models.IntegerField(db_column='Id_empleado')),
            ],
            options={
                'db_table': 'bodega_lamerica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesDeLamerica',
            fields=[
                ('id_usuario', models.IntegerField(db_column='Id_usuario', primary_key=True, serialize=False)),
                ('nombre_de_clinte', models.CharField(blank=True, db_column='Nombre_de_clinte', max_length=100, null=True)),
                ('numero_telefonico', models.CharField(blank=True, db_column='Numero_telefonico', max_length=20, null=True)),
                ('correo_electronico', models.CharField(blank=True, db_column='Correo_electronico', max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=100, null=True)),
                ('fecha_de_nacimiento', models.DateField(blank=True, db_column='Fecha_de_nacimiento', null=True)),
                ('productos_que_compra', models.CharField(blank=True, db_column='Productos_que_compra', max_length=500, null=True)),
                ('cantidad_de_productos', models.IntegerField(blank=True, db_column='Cantidad_De_productos', null=True)),
            ],
            options={
                'db_table': 'clientes_de_lamerica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpleadosLamerica',
            fields=[
                ('id_empleado', models.IntegerField(db_column='Id_empleado', primary_key=True, serialize=False)),
                ('cargo_empleado', models.CharField(blank=True, db_column='Cargo_empleado', max_length=50, null=True)),
                ('nombre_empleado', models.CharField(blank=True, db_column='Nombre_empleado', max_length=50, null=True)),
                ('apellido_empleado', models.CharField(blank=True, db_column='Apellido_empleado', max_length=50, null=True)),
                ('correo_de_empleado', models.CharField(blank=True, db_column='Correo_de_empleado', max_length=50, null=True)),
                ('direccion_empleado', models.CharField(blank=True, db_column='Direccion_empleado', max_length=50, null=True)),
                ('id_bodega', models.IntegerField(blank=True, db_column='Id_bodega', null=True)),
                ('ubicacion_de_bodega', models.CharField(blank=True, db_column='Ubicacion_de_bodega', max_length=50, null=True)),
                ('documento_de_identidad', models.IntegerField(db_column='Documento_De_identidad')),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'empleados_lamerica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentasDeLamerica',
            fields=[
                ('id_venta', models.IntegerField(db_column='Id_venta', primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField(blank=True, db_column='Id_usuario', null=True)),
                ('id_bodega', models.IntegerField(blank=True, db_column='Id_Bodega', null=True)),
                ('id_inventario', models.IntegerField(blank=True, db_column='Id_inventario', null=True)),
                ('costo_pedido', models.DecimalField(blank=True, db_column='Costo_pedido', decimal_places=2, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(blank=True, db_column='Metodo_pago', max_length=100, null=True)),
                ('id_pago', models.IntegerField(blank=True, db_column='Id_pago', null=True)),
            ],
            options={
                'db_table': 'ventas_de_lamerica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioDeLamerica',
            fields=[
                ('id_inventario', models.IntegerField(db_column='Id_inventario', primary_key=True, serialize=False)),
                ('id_productos', models.IntegerField(blank=True, db_column='Id_productos', null=True)),
                ('numero_de_productos', models.IntegerField(blank=True, db_column='Numero_de_productos', null=True)),
                ('fecha_de_ingreso_de_productos', models.DateField(blank=True, db_column='Fecha_de_ingreso_de_productos', null=True)),
                ('fecha_de_vencimiento_de_productos', models.DateField(blank=True, db_column='Fecha_de_vencimiento_de_productos', null=True)),
            ],
            options={
                'db_table': 'inventario_de_lamerica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidosEnProceso',
            fields=[
                ('id_pedido', models.IntegerField(db_column='Id_pedido', primary_key=True, serialize=False)),
                ('fecha_de_pedido', models.DateField(blank=True, db_column='Fecha_de_pedido', null=True)),
                ('estado_de_pedido', models.CharField(blank=True, db_column='Estado_de_pedido', max_length=50, null=True)),
                ('detalles_de_pedido', models.CharField(blank=True, db_column='Detalles_de_pedido', max_length=200, null=True)),
                ('costo_pedido', models.DecimalField(blank=True, db_column='Costo_pedido', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'pedidos_en_proceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedoresLamerica',
            fields=[
                ('id_proveedor', models.IntegerField(db_column='Id_proveedor', primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(blank=True, db_column='Nombre_proveedor', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('ubicacion_proveedor', models.CharField(blank=True, db_column='Ubicacion_proveedor', max_length=100, null=True)),
                ('productos', models.IntegerField(blank=True, db_column='Productos', null=True)),
                ('precio_productos', models.DecimalField(blank=True, db_column='Precio_productos', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'proveedores_lamerica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudesAcceso',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('numero_empleado', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('atendida', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitudes_acceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('stock_minimo', models.IntegerField(default=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnviosLamerica',
            fields=[
                ('id_envio', models.OneToOneField(db_column='Id_envio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gesym.ventasdelamerica')),
                ('fecha_envio', models.DateField(blank=True, db_column='Fecha_envio', null=True)),
                ('numero_de_guia', models.IntegerField(blank=True, db_column='Numero_de_guia', null=True)),
                ('ciudad_de_salida', models.CharField(blank=True, db_column='Ciudad_de_salida', max_length=100, null=True)),
                ('ciudad_de_destino', models.CharField(blank=True, db_column='Ciudad_de_destino', max_length=100, null=True)),
                ('id_venta', models.IntegerField(blank=True, db_column='Id_venta', null=True)),
                ('id_pedido', models.IntegerField(blank=True, db_column='Id_pedido', null=True)),
                ('empresa_de_transporte', models.CharField(blank=True, db_column='Empresa_de_transporte', max_length=100, null=True)),
            ],
            options={
                'db_table': 'envios_lamerica',
                'managed': False,
            },
        ),
    ]
