# Generated by Django 6.0.6 on 2026-07-09 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesym', '0002_cliente_venta_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('codigo_producto', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Ajuste de inventario', 'Ajuste de inventario')], max_length=30)),
                ('motivo', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.IntegerField()),
                ('usuario_nombre', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gesym.producto')),
            ],
        ),
    ]
