# Generated by Django 6.0.6 on 2026-08-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesym', '0012_producto_tipo_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='numero_bandejas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_bandeja',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
