from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('', RedirectView.as_view(url='login/', permanent=False)),
    path('login/', views.login_view, name='login'),
    path('recuperar/', views.recuperar_view, name='recuperar'),
    path('solicitud/', views.solicitud_view, name='solicitud'),
    path('registro/', views.registro_view, name='registro'),
    path('solicitudes-pendientes/', views.solicitudes_pendientes_view, name='solicitudes_pendientes'),
    path('solicitudes/aprobar/<int:solicitud_id>/', views.aprobar_solicitud_view, name='aprobar_solicitud'),
    path('solicitudes/rechazar/<int:solicitud_id>/', views.rechazar_solicitud_view, name='rechazar_solicitud'),
    path('soporte/', views.soporte_view, name='soporte'),
    path('soporte-pendientes/', views.soporte_pendientes_view, name='soporte_pendientes'),
    path('soporte/atender/<int:solicitud_id>/', views.atender_soporte_view, name='atender_soporte'),
    path('soporte/descartar/<int:solicitud_id>/', views.descartar_soporte_view, name='descartar_soporte'),
    path('usuarios/', views.usuarios_view, name='usuarios'),
    path('usuarios/eliminar/<int:usuario_id>/', views.eliminar_usuario_view, name='eliminar_usuario'),
    path('usuarios/editar/<int:usuario_id>/', views.editar_usuario_view, name='editar_usuario'),
    path('inicio/', views.inicio_view, name='inicio'),
    path('inventario/', views.inventario_view, name='inventario'),
    path('inventario/agregar/', views.agregar_producto_view, name='agregar_producto'),
    path('inventario/editar/<int:producto_id>/', views.editar_producto_view, name='editar_producto'),
    path('inventario/eliminar/<int:producto_id>/', views.eliminar_producto_view, name='eliminar_producto'),
    path('compras/', views.compras_view, name='compras'),
    path('clientes/', views.clientes_view, name='clientes'),
    path('clientes/agregar/', views.agregar_cliente_view, name='agregar_cliente'),
    path('clientes/editar/<int:cliente_id>/', views.editar_cliente_view, name='editar_cliente'),
    path('clientes/eliminar/<int:cliente_id>/', views.eliminar_cliente_view, name='eliminar_cliente'),
    path('informes/', views.informes_view, name='informes'),
    path('acerca/', views.acerca_view, name='acerca'),
    path('logout/', views.logout_view, name='logout'),
    path('inventario/', views.inventario_view, name='inventario'),
    path('inventario/agregar/', views.agregar_producto_view, name='agregar_producto'),
    path('inventario/editar/<int:producto_id>/', views.editar_producto_view, name='editar_producto'),
    path('inventario/eliminar/<int:producto_id>/', views.eliminar_producto_view, name='eliminar_producto'),
    path('compras/agregar/', views.agregar_venta_view, name='agregar_venta'),
    path('compras/editar/<int:venta_id>/', views.editar_venta_view, name='editar_venta'),
    path('compras/eliminar/<int:venta_id>/', views.eliminar_venta_view, name='eliminar_venta'),
    path('informes/exportar-compras-excel/', views.exportar_compras_excel_view, name='exportar_compras_excel'),
    path('bodega/seleccionar/', views.seleccionar_bodega_view, name='seleccionar_bodega'),
    path('bodegas/', views.bodegas_view, name='bodegas'),
    path('bodegas/agregar/', views.agregar_bodega_view, name='agregar_bodega'),
    path('bodegas/editar/<int:bodega_id>/', views.editar_bodega_view, name='editar_bodega'),
    path('bodegas/eliminar/<int:bodega_id>/', views.eliminar_bodega_view, name='eliminar_bodega'),
    path('bodegas/reiniciar/<int:bodega_id>/', views.reiniciar_bodega_view, name='reiniciar_bodega'),
]